'use client';
import { motion } from 'framer-motion';

import styles from './grid.module.css';
import SmallDayCard from '../day-card/small-card/small-day-card';
import ImageCard from '../image-card/image-card';
import BigCard from '../day-card/big-card/big-card';
import SantaCard from '../day-card/santa-card/santa-card';
import { useEffect, useState } from 'react';
import { SantaDay } from '../../api/santa-days/santaDay';

export interface GridProps {
  santaDays: SantaDay[];
}

export default function Grid({ santaDays }: GridProps) {
  const [isVisible, setIsVisible] = useState('none');

  useEffect(() => {
    const timer = setTimeout(() => setIsVisible('grid'), 0);
    return () => clearTimeout(timer);
  }, []);

  let currentY = 1;

  return (
    <div>
      <motion.div
        style={{ display: isVisible }}
        className={styles['grid-container']}
      >
        <div className={styles['grid']}>
          <SmallDayCard
            x={1}
            isOpened={santaDays[0].isOpened}
            y={1}
            day={1}
            placeSelf={'start'}
          />
          <ImageCard
            x={7}
            y={currentY}
            marginY={0}
            delay={0.1}
            rotate={'6deg'}
            placeSelf={'end'}
            width={160}
            uri={'/img/1-pic.jpg'}
          />
          <ImageCard
            x={4}
            y={++currentY}
            marginY={-250}
            marginX={-25}
            delay={0.2}
            rotate={'0deg'}
            placeSelf={'center'}
            width={50}
            uri={'/img/bauble-7.png'}
          />
          <SmallDayCard
            day={2}
            delay={0.3}
            isOpened={santaDays[1].isOpened}
            x={7}
            y={currentY}
            marginY={40}
            placeSelf={'end'}
            alignSelf={'start'}
          />
          <ImageCard
            x={1}
            y={currentY}
            delay={0.4}
            marginY={80}
            marginX={20}
            rotate={'5deg'}
            placeSelf={'start'}
            width={150}
            uri={'/img/6-pic.jpg'}
          />
          <ImageCard
            x={6}
            y={++currentY}
            marginY={-120}
            delay={0.5}
            rotate={'-3deg'}
            placeSelf={'start'}
            width={100}
            uri={'/img/bauble-1.png'}
          />
          <ImageCard
            x={6}
            y={currentY}
            marginY={0}
            marginX={-50}
            delay={0.6}
            rotate={'10deg'}
            placeSelf={'start'}
            width={50}
            uri={'/img/bauble-3.png'}
          />
          <SmallDayCard
            day={3}
            isOpened={santaDays[2].isOpened}
            x={2}
            y={currentY}
            marginX={15}
            delay={0.7}
            marginY={50}
            alignSelf={'start'}
            placeSelf={'center'}
          />
          <ImageCard
            x={5}
            y={currentY}
            rotate={'-3deg'}
            placeSelf={'start'}
            delay={0.8}
            marginY={90}
            width={150}
            uri={'/img/2-pic.jpg'}
          />
          <ImageCard
            x={2}
            y={++currentY}
            marginY={0}
            marginX={-30}
            rotate={'70deg'}
            placeSelf={'start'}
            width={100}
            uri={'/img/lights.png'}
          />
          <ImageCard
            x={5}
            y={currentY}
            marginY={0}
            marginX={30}
            rotate={'120deg'}
            placeSelf={'start'}
            width={100}
            uri={'/img/lights.png'}
          />
          <ImageCard
            x={2}
            y={++currentY}
            marginY={40}
            marginX={-30}
            rotate={'10deg'}
            placeSelf={'start'}
            width={140}
            uri={'/img/giftbox.png'}
          />
          <SmallDayCard
            day={4}
            isOpened={santaDays[3].isOpened}
            x={6}
            y={currentY}
            marginY={30}
            placeSelf={'center'}
          />
          <ImageCard
            x={7}
            y={currentY}
            marginY={20}
            marginX={0}
            rotate={'20deg'}
            width={50}
            uri={'/img/bauble-1.png'}
          />
          <BigCard
            day={5}
            isOpened={santaDays[4].isOpened}
            x={2}
            y={++currentY}
            marginY={50}
            placeSelf={'start'}
          />
          <ImageCard
            x={7}
            y={currentY}
            marginY={-80}
            rotate={'-6deg'}
            placeSelf={'center'}
            width={90}
            uri={'/img/bauble-4.png'}
          />
          <ImageCard
            x={1}
            y={++currentY}
            marginY={30}
            rotate={'20deg'}
            placeSelf={'start'}
            width={100}
            uri={'/img/lights.png'}
          />
          <ImageCard
            x={1}
            y={currentY}
            marginY={190}
            rotate={'70deg'}
            placeSelf={'start'}
            width={100}
            uri={'/img/lights.png'}
          />
          <ImageCard
            x={4}
            y={currentY}
            marginY={50}
            marginX={0}
            rotate={'5deg'}
            width={180}
            placeSelf={'start'}
            uri={'/img/7-pic.jpg'}
          />
          <SmallDayCard
            day={6}
            isOpened={santaDays[5].isOpened}
            x={1}
            y={++currentY}
            marginY={30}
          />
          <SmallDayCard
            day={7}
            isOpened={santaDays[6].isOpened}
            x={7}
            y={++currentY}
            marginY={40}
            placeSelf={'end'}
          />
          <ImageCard
            x={1}
            y={++currentY}
            marginY={0}
            rotate={'-6deg'}
            placeSelf={'start'}
            width={180}
            uri={'/img/3-pic.jpg'}
          />
          <SmallDayCard
            day={8}
            isOpened={santaDays[7].isOpened}
            x={3}
            y={++currentY}
            marginY={160}
          />
          <SmallDayCard
            day={9}
            isOpened={santaDays[8].isOpened}
            x={6}
            y={++currentY}
            marginY={150}
            placeSelf={'center'}
          />
          <BigCard
            day={10}
            isOpened={santaDays[9].isOpened}
            x={4}
            y={++currentY}
            marginY={150}
            placeSelf={'center'}
          />
          <SmallDayCard
            day={11}
            isOpened={santaDays[10].isOpened}
            x={1}
            y={++currentY}
            marginY={100}
          />
          <SmallDayCard
            day={12}
            isOpened={santaDays[11].isOpened}
            x={5}
            y={++currentY}
            marginY={200}
          />
          <SmallDayCard
            day={13}
            isOpened={santaDays[12].isOpened}
            x={2}
            y={++currentY}
            marginY={150}
          />
          <SmallDayCard
            day={14}
            isOpened={santaDays[13].isOpened}
            x={4}
            y={++currentY}
            marginY={250}
            placeSelf={'end'}
          />
          <BigCard
            day={15}
            isOpened={santaDays[14].isOpened}
            x={4}
            y={++currentY}
            marginY={150}
            placeSelf={'center'}
          />
          <SmallDayCard
            day={16}
            isOpened={santaDays[15].isOpened}
            x={5}
            y={++currentY}
            marginY={200}
          />
          <SmallDayCard
            day={17}
            isOpened={santaDays[16].isOpened}
            x={1}
            y={++currentY}
            marginY={150}
          />
          <SmallDayCard
            day={18}
            isOpened={santaDays[17].isOpened}
            x={5}
            y={++currentY}
            marginY={150}
          />
          <SmallDayCard
            day={19}
            isOpened={santaDays[18].isOpened}
            x={3}
            y={++currentY}
            marginY={150}
            placeSelf={'end'}
          />
          <BigCard
            day={20}
            isOpened={santaDays[19].isOpened}
            x={4}
            y={++currentY}
            marginY={150}
            placeSelf={'center'}
          />
          <SmallDayCard
            day={21}
            isOpened={santaDays[20].isOpened}
            x={1}
            y={++currentY}
            marginY={150}
          />
          <SmallDayCard
            day={22}
            isOpened={santaDays[21].isOpened}
            x={7}
            y={++currentY}
            marginY={150}
            placeSelf={'end'}
          />
          <SmallDayCard
            day={23}
            isOpened={santaDays[22].isOpened}
            x={3}
            y={++currentY}
            marginY={150}
          />
          <SmallDayCard
            day={24}
            isOpened={santaDays[23].isOpened}
            x={4}
            y={++currentY}
            marginY={150}
          />
          <SantaCard
            day={25}
            isOpened={santaDays[24].isOpened}
            x={3}
            y={++currentY}
            marginX={-15}
            marginY={90}
            placeSelf={'center'}
          />
          <ImageCard
            x={2}
            y={currentY}
            marginY={108}
            rotate={'4deg'}
            width={65}
            uri={'/img/secret-santa.png'}
          />
          <ImageCard
            x={2}
            y={++currentY}
            placeSelf={'center'}
            rotate={'0deg'}
            alignSelf={'end'}
            width={80}
            uri={'/img/gift-bag.png'}
          />
          <ImageCard
            x={7}
            y={currentY}
            marginY={-50}
            rotate={'0deg'}
            placeSelf={'end'}
            width={180}
            uri={'/img/christmas-tree.png'}
          />
        </div>
      </motion.div>
    </div>
  );
}
